version: "3"
services:
  app:
    build: ./
    image: orendin8/devops_project
    ports:
     - "5000:5000"
    env_file:
    - ./.env
     
  db:
    image: mysql:8.0.21
    ports:
     - "30000:3306"
    
    environment:
     MYSQL_ROOT_HOST: ${mysql_host}
     MYSQL_ROOT_USER: ${mysql_username}
     MYSQL_ROOT_PASSWORD: ${mysql_password}
     MYSQL_DATABASE: ${mysql_database}
    volumes:
     - ./db:/docker-entrypoint-initdb.d/:ro
     
       
