version: "3"
services:
  app:
    build: ./
    ports:
     - "5000:5000"
     
  db:
    image: mysql:8.0.21
    ports:
     - "30000:3306"
   
    volumes:
     - ./db:/docker-entrypoint-initdb.d/:ro
       
