version: "3"
services:
  app:
    build: ./
    ports:
     - "5000:5000"
     
  db:
    image: mysql:8.0.21
    ports:
     - "30000:3306"
     environment: 
        MYSQL_ROOT_HOST: ${localhost}
        MYSQL_ROOT_USER: ${oreng}
        MYSQL_ROOT_PASSWORD: ${og123456}
        MYSQL_DATABASE: ${attendance}
   
    volumes:
     - ./db:/docker-entrypoint-initdb.d/:ro
       
